src/__csp-nonce.ts

This PR simplifies the excludedPaths regexes by joining all of the excluded extensions into a single regex, vs spreading them into multiple. In turns out that joining all into a single regex is much more performant ([Slack thread](https://netlify.slack.com/archives/C0183KVDHFH/p1692831720217969?thread_ts=1692696298.268039&cid=C0183KVDHFH)). Closes #46 
To test, go to https://deploy-preview-49--csp-nonce.netlify.app, and with a clean/fresh browser cache, inspect the response headers for the document html, and for the 404ing favicon.ico. The document html should have the `x-debug-csp-nonce: invoked` response header, whereas the favicon.ico resource should not. 
You can try this on https://deploy-preview-18839--app.netlify.com too -- only the document html should have `x-debug-csp-nonce: …

fix(perf): join excluded extensions into one regex instead of spreading into multiple regexes

---

src/__csp-nonce-inputs.json
src/__csp-nonce.ts

This PR uses WASM-based https://workers.tools/html-rewriter/ instead of a regular expression to perform the HTML body transformation, which simplifies code and should give a minor perf boost. Closes #45 
Tested on https://deploy-preview-18839--app.netlify.com, as well as https://deploy-preview-48--csp-nonce.netlify.app!

fix(perf): use HTMLRewriter instead of regex for html transformation

---

src/__csp-nonce.ts

We saw an error in a user's deploy (helpdesk ticket: https://netlify.zendesk.com/agent/tickets/200248) that said:
```
Packaging Edge Functions from netlify/edge-functions directory:
- __csp-nonce
TypeError: params.excludedPath is not iterable
at file:///opt/build/repo/netlify/edge-functions/__csp-nonce.ts:179:15
```
Looking at the code, the types for `params.excludedPath` say it can be a `string | Array<string>`. In case the property is a string, `...params.excludedPath` would simply make the string unusable for the config. For example:
```ts
const foo = 'bar'
console.log(...foo) // b a r
```
Since we need an array, I think it's best to just concat the 2 arrays (or an array and a string) together as they'd both produce the expected results.
Any thoughts?

fix: excludedPath not iterable

---

site/index.html
site/main.css
src/__csp-nonce.ts

This PR fixes #58 by also adding the nonce to `<link rel="preload" as="script" />` elements. It also adds a case to the site's index.html file so that we can test that it is indeed adding the nonce in the site's Deploy Previews.

fix: add nonce to link preload tags

---

site/_headers
site/index.html
src/__csp-nonce.ts

This should fix the issue reported in https://github.com/netlify/plugin-csp-nonce/issues/72

fix: missing leading space before user-supplied value

---

src/__csp-nonce.ts

This fixes an issue where the edge function would be invoked if the path was encoded like `/.netlify%2Ffunctions/`.

fix: remove trailing slash from .netlify excluded path

---

src/__csp-nonce.ts

See https://github.com/worker-tools/html-rewriter/issues/6. We suspect that html_rewriter has a memory leak on high usage, and with a bit of luck this dependency upgrade fixes it.
Part of https://linear.app/netlify/issue/COM-687/new-relic-or-edge-functions-failing-w-error-recursive-use-of-an-object.

fix: upgrade html_rewriter

---

src/__csp-nonce.ts

This function should only be run its main logic if the request is a HTTP GET. By returning early instead of using `context.next(request)`, we avoid having the request go through this edge function, which will reduce the overall CPU and memory usage of this function.
Note that this behavior of returning `undefined` to bypass an Edge Function is documented behavior, it is safe to rely on this. It's documented on https://docs.netlify.com/edge-functions/api/:
```
The expected return value is one of the following:
a standard Response object representing the HTTP response to be delivered to the client
a standard URL object if you want to rewrite the incoming request to another same-site URL with a 200 status code
undefined if you choose to bypass the current function
```

fix(perf): return early if the request is not a HTTP GET

---

src/__csp-nonce.ts

previously we were handling this in the function implementation by checking the method and returning early is if was not a GET.  we can do better than this however, and configure the function to only be invoked if the request method is a GET.

fix: update the config to only ever run the function for HTTP GET requests

---

src/__csp-nonce.ts

this is a tiny performance optimisation. Previously we would declare and initialise the `header` variable, and we might not have used it because the response could be non-html.
this patch relocates this variable declaration to happen after we have figured out the response is html

fix(refactor): only declare and initialise the `header` variable if we are going to use it

---

src/__csp-nonce.ts

`"text/html"` should be the only value that we act against as that is the only entry in the IANA text type registry which indicates HTML content (https://www.iana.org/assignments/media-types/media-types.xhtml#text).
Also, the HTTP header/field values can not begin or end with whitespace (https://www.rfc-editor.org/rfc/rfc9110.html#section-5.5), which is why we can use a strict equality against the exact string "text/html".

fix(perf): refactor the content-type check from `startsWith("text/html")` to `=== "text/html"`

---

index.js
package-lock.json
package.json

Always include the `/.netlify/image` path in the `excludedPaths` array.
If the project is using NextJS, then also include `/_next/image` in the `excludedPaths` array. The reason this is only done for NextJS projects is because for projects not using NextJS, we would not know ahead of time what content-type this path would respond with, for example it could be responding with a 404 HTML page, which we would want to invoke the CSP Edge Function for.

feat(perf): Do not invoke the CSP Edge Function for Netlify Image CDN requests

---

src/__csp-nonce.ts

Reverts netlify/plugin-csp-nonce#85
I forgot that the content-type can include an optional charset directive, E.G. `text/html; charset=UTF-8`
We need to revert this PR to as it broke the CSP plugin - I will do a separate PR which adds a bunch of integration tests so we don't regress again

Revert "fix(perf): refactor the content-type check from `startsWith("text/html")` to `=== "text/html"`"

---

src/__csp-nonce.ts

[csp_nonce_html_transformer](https://github.com/JakeChampion/csp_nonce_html_transformer/) internally has a custom non-asyncify wasm build of lol-html which only includes the setAttribute method, as that is all that is needed to add nonce attributes to elements. This reduces the wasm size by ~70%. It is also using the latest v2.0.0 of lol-html.
[csp_nonce_html_transformer](https://github.com/JakeChampion/csp_nonce_html_transformer/) is a standalone library for Deno which takes in a Response instance and will add CSP directives to the configured CSP header and will add nonce attributes to the response body.

fix(refactor): use csp_nonce_html_transformer library

---

package-lock.json
src/__csp-nonce.ts
tests/integration/test.test.ts

I was able to reproduce the [edge function crash](https://linear.app/netlify/issue/CPLA-2262/csp-plugin-causes-recursive-use-of-an-object-detected-which-would-lead#comment-51aafd01) issue with csp_nonce_html_transformer@v2.1.1.
With csp_nonce_html_transformer@v2.1.4 I am no longer able to reproduce and hopefully this will solve our CSP issue.
Next step would be to publish the new csp plugin and test it out on the netlify-react-ui

fix: Bump csp nonce html rewriter version

---

src/__csp-nonce.ts

We ran into issues with cypress tests when running in the netlify react app.
I was able to reproduce by running the react app locally and when removing the request out of `context.next()` it worked.
By default `context.next()` will continue down the request chain, which is what we want.

fix: Continue down request chain to get response

---

index.js
tests/integration/helpers.ts

When running the plugin with the netlify-react-ui locally or running the circle ci tests would fail. This is because netlify-react-ui would run the csp edge function before the page was even bundled.
without this change running react-ui locally would break

fix: inject function only on prebuild

---

src/__csp-nonce.ts

Netlify Edge Functions are not able to read the file-system, which means we can't read the generated .wasm file during execution, we currently fetch the wasm file over the network but this request could fail or have an incorrect response, leading to a runtime error when attempting to instantiate the WebAssembly Module. To work-around this, the library was updated to include a .ts file which includes the exact same bytes as the wasm file, but within a JavaScript UInt8Array, which we can then instantiate as a WebAssembly Module.
This will resolve the occassional errors we see along the lines of:
>**Unhandled error**
>CompileError: WebAssembly.instantiate(): expected magic word 00 61 73 6d, found 35 30 30 3a @+0
>**Location**
>https://deno.land/x/csp_nonce_html_transformer@v2.1.5/pkg/html_rew …

fix: use entrypoint which embeds the wasm instead of requiring it to be fetched over the network when deployed as a Netlify Edge Function

---

package-lock.json
package.json

The breaking changes in `@netlify/build-info` don't impact usage in this plugin https://github.com/netlify/plugin-csp-nonce/blob/4f1e0855c39a90a1f524608e5b95c6f3420ffaf5/index.js#L10
So this is just to ensure ~latest is being used to not miss any potential future updates.
https://github.com/netlify/build/pull/5962 was change requiring major version bump

fix: update @netlify/build-info to v8.0.0

---

src/__csp-nonce.ts

In this patch we are changing the function to catch all the throws and return undefined in those situations. The reason we do this is because returning undefined will cause the next edge function in the chain to be executed. This is equivalent to setting the Edge Function's `config.onError` property to "bypass", but is handled completely by the Edge Function instead of by something else.

fix: Explicitly implement error bypass behavior instead of relying on the platform
